version: "3.8"

services:
  django:
    restart: unless-stopped
    build: .
    container_name: django
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  db:
    restart: always
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5432:5432"


volumes:
  pgdata: