# Generated by Django 4.2.6 on 2023-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_id',
            field=models.PositiveIntegerField(default=None, verbose_name='Номер вопроса'),
            preserve_default=False,
        ),
    ]
